# Generated by Django 6.1.1 on 2026-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True, verbose_name='Product Name')),
                ('description', models.TextField(null=True)),
                ('production_date', models.DateField(null=True, verbose_name='Production Date')),
                ('image', models.ImageField(null=True, upload_to='media/product_img')),
                ('product_type', models.CharField(choices=[('Fruits', 'Fruits'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Gadget', 'Gadget')], max_length=40, null=True, verbose_name='Product Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
        ),
    ]
